server:
  port: 8080
  servlet:
    session:
      persistent: false
      timeout: 3600
    context-path:
spring:
  main:
    allow-circular-references: true
  mvc:
    view:
      prefix: /
      suffix: .jsp
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    driver-class-name: com.ibm.as400.access.AS400JDBCDriver
    url: jdbc:as400://192.168.212.231/CPID
    username: rustam
    password: 9061648
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      idle-timeout: 10000
      maximum-pool-size: 5
      minimum-idle: 5
      pool-name: edo
      connection-test-query: select current_timestamp cts from sysibm.sysdummy1
      data-source-properties: useUnicode=true&characterEncoding=UTF-8
